# Generated by Django 3.0.6 on 2020-05-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('is_done', models.BooleanField(default=False)),
                ('priority', models.SmallIntegerField(default=1)),
                ('expiry_date', models.DateTimeField(null=True, verbose_name='deadline')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.Project')),
            ],
            options={
                'ordering': ['board', 'priority'],
            },
        ),
    ]
