# Generated by Django 3.0.5 on 2020-04-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expiry_date',
            field=models.DateTimeField(verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(default=1),
        ),
    ]
